#!/usr/bin/env python3
import socket,sys,json
from pathlib import Path
s=socket.socket(socket.AF_UNIX,socket.SOCK_STREAM);s.settimeout(8)
s.connect(str(Path.home()/'.local/state/flow-remote-bridge/receiver.sock'))
data=sys.stdin.buffer.readline(524290)
if len(data)>524288:raise SystemExit('Request too large')
s.sendall(data.rstrip(b'\n')+b'\n');s.shutdown(socket.SHUT_WR)
r=b''
while True:
 b=s.recv(4096)
 if not b:break
 r+=b
print(r.decode())
